// Advance widths of the pixel font, as Pillow measures them at 40px.
//
// Generated by tools/export_font_metrics.py - do not edit by hand.
//
// The native editor measures text with these so its line breaks land in
// exactly the same place as the Python renderer and the browser. raylib
// rasterises the same font about two per cent narrower, which is invisible
// but quite enough to move a wrap.

#pragma once

namespace font_metrics {

constexpr int SIZE = 40;
constexpr int ASCENT = 43;
constexpr int DESCENT = 10;
constexpr int LINE_HEIGHT = 60;

// Indexed by codepoint. Anything outside the table falls back to FALLBACK.
constexpr int FIRST = 32;
constexpr int LAST = 255;

constexpr float ADVANCE[] = {
    13.0f, 5.0f, 10.0f, 23.0f, 15.0f, 18.0f, 20.0f, 5.0f, 10.0f, 10.0f,
    11.0f, 21.0f, 8.0f, 18.0f, 5.0f, 13.0f, 17.0f, 16.0f, 15.0f, 15.0f,
    18.0f, 15.0f, 15.0f, 15.0f, 15.0f, 15.0f, 5.0f, 8.0f, 15.0f, 21.0f,
    15.0f, 15.0f, 25.0f, 24.0f, 18.0f, 15.0f, 18.0f, 16.0f, 15.0f, 15.0f,
    21.0f, 11.0f, 16.0f, 21.0f, 18.0f, 26.0f, 21.0f, 18.0f, 18.0f, 18.0f,
    21.0f, 15.0f, 15.0f, 21.0f, 24.0f, 31.0f, 23.0f, 21.0f, 15.0f, 8.0f,
    13.0f, 8.0f, 15.0f, 16.0f, 10.0f, 18.0f, 18.0f, 15.0f, 18.0f, 15.0f,
    15.0f, 15.0f, 21.0f, 11.0f, 13.0f, 19.0f, 11.0f, 26.0f, 21.0f, 15.0f,
    15.0f, 16.0f, 13.0f, 15.0f, 13.0f, 21.0f, 21.0f, 26.0f, 21.0f, 21.0f,
    15.0f, 10.0f, 5.0f, 10.0f, 15.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 18.0f, 5.0f,
    18.0f, 21.0f, 23.0f, 21.0f, 5.0f, 15.0f, 10.0f, 20.0f, 18.0f, 18.0f,
    18.0f, 13.0f, 20.0f, 13.0f, 10.0f, 16.0f, 10.0f, 13.0f, 8.0f, 18.0f,
    24.0f, 5.0f, 8.0f, 10.0f, 15.0f, 18.0f, 18.0f, 18.0f, 18.0f, 15.0f,
    23.0f, 24.0f, 24.0f, 23.0f, 24.0f, 24.0f, 30.0f, 15.0f, 16.0f, 16.0f,
    16.0f, 16.0f, 11.0f, 10.0f, 10.0f, 10.0f, 18.0f, 21.0f, 18.0f, 18.0f,
    18.0f, 18.0f, 18.0f, 15.0f, 18.0f, 20.0f, 22.0f, 21.0f, 21.0f, 21.0f,
    18.0f, 16.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 25.0f, 15.0f,
    15.0f, 15.0f, 15.0f, 15.0f, 11.0f, 10.0f, 10.0f, 10.0f, 15.0f, 21.0f,
    15.0f, 15.0f, 15.0f, 15.0f, 15.0f, 16.0f, 15.0f, 20.0f, 22.0f, 21.0f,
    21.0f, 21.0f, 18.0f, 21.0f,
};

constexpr float FALLBACK = 21.0f;

inline float advance(int codepoint) {
    if (codepoint < FIRST || codepoint > LAST) return FALLBACK;
    return ADVANCE[codepoint - FIRST];
}

}  // namespace font_metrics
