"""Write out the font's advance widths for the native build.

Pillow sizes a font by its em square and raylib rasterises to a pixel height,
so asking both for "40" gives text that is about two per cent apart. That is
invisible to look at, but it is enough to flip a line break, and a line
breaking in a different place is very visible indeed.

So the native editor measures with these numbers - the same ones the Python
renderer and the browser use - and leaves raylib to do the drawing.

    python tools/export_font_metrics.py
"""

import sys
from pathlib import Path

from PIL import ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "assets" / "fonts" / "pixelplay.ttf"
HEADER = ROOT / "native" / "src" / "font_metrics.h"

FONT_SIZE = 40


def main() -> int:
    """Emit a header holding one advance per codepoint."""
    if not FONT.exists():
        print(f"Font not found: {FONT}")
        return 1

    font = ImageFont.truetype(str(FONT), FONT_SIZE)

    # Latin-1 covers every report written so far, accents included.
    codepoints = list(range(32, 127)) + list(range(0xA0, 0x100))
    advances = {code: font.getlength(chr(code)) for code in codepoints}

    ascent, descent = font.getmetrics()
    line_height = int((ascent + descent) * 1.15)

    lines = [
        "// Advance widths of the pixel font, as Pillow measures them at "
        f"{FONT_SIZE}px.",
        "//",
        "// Generated by tools/export_font_metrics.py - do not edit by hand.",
        "//",
        "// The native editor measures text with these so its line breaks land in",
        "// exactly the same place as the Python renderer and the browser. raylib",
        "// rasterises the same font about two per cent narrower, which is invisible",
        "// but quite enough to move a wrap.",
        "",
        "#pragma once",
        "",
        "namespace font_metrics {",
        "",
        f"constexpr int SIZE = {FONT_SIZE};",
        f"constexpr int ASCENT = {ascent};",
        f"constexpr int DESCENT = {descent};",
        f"constexpr int LINE_HEIGHT = {line_height};",
        "",
        "// Indexed by codepoint. Anything outside the table falls back to FALLBACK.",
        f"constexpr int FIRST = {min(codepoints)};",
        f"constexpr int LAST = {max(codepoints)};",
        "",
        "constexpr float ADVANCE[] = {",
    ]

    row: list[str] = []
    for code in range(min(codepoints), max(codepoints) + 1):
        row.append(f"{advances.get(code, 0.0):.1f}f,")
        if len(row) == 10:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))

    fallback = advances.get(ord("n"), float(FONT_SIZE) / 2)
    lines += [
        "};",
        "",
        f"constexpr float FALLBACK = {fallback:.1f}f;",
        "",
        "inline float advance(int codepoint) {",
        "    if (codepoint < FIRST || codepoint > LAST) return FALLBACK;",
        "    return ADVANCE[codepoint - FIRST];",
        "}",
        "",
        "}  // namespace font_metrics",
        "",
    ]

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {HEADER.relative_to(ROOT)}")
    print(f"  {len(codepoints)} codepoints, ascent {ascent}, line height {line_height}")

    check = "The Ministry of Income has discovered an anomaly in your earnings."
    print(f"  reference width of the sample line: {font.getlength(check):.1f}px")
    return 0


if __name__ == "__main__":
    sys.exit(main())
